package fe.tldlib.__tld_gen

import fe.tldlib.ITldNode
import fe.tldlib.TldNode
import fe.tldlib.LeavesTldNode
import fe.tldlib.TldBase

internal class O_m_tlds : TldBase {
    override fun getTlds(): Map<String, ITldNode> {
        return mapOf("ma" to LeavesTldNode("co","net","gov","org","ac","press"),"mc" to LeavesTldNode("tm","asso"),TldNode.childless("md"),"me" to LeavesTldNode("co","net","org","edu","ac","gov","its","priv"),"mg" to LeavesTldNode("org","nom","gov","prd","tm","edu","mil","com","co"),TldNode.childless("mh"),TldNode.childless("mil"),"mk" to LeavesTldNode("com","org","net","edu","gov","inf","name"),"ml" to LeavesTldNode("com","edu","gouv","gov","net","org","presse"),TldNode.childless("mm"),"mn" to LeavesTldNode("gov","edu","org"),"mo" to LeavesTldNode("com","net","org","edu","gov"),TldNode.childless("mobi"),TldNode.childless("mp"),TldNode.childless("mq"),"mr" to LeavesTldNode("gov"),"ms" to LeavesTldNode("com","edu","gov","net","org"),"mt" to LeavesTldNode("com","edu","net","org"),"mu" to LeavesTldNode("com","net","org","gov","ac","co","or"),TldNode.childless("museum"),"mv" to LeavesTldNode("aero","biz","com","coop","edu","gov","info","int","mil","museum","name","net","org","pro"),"mw" to LeavesTldNode("ac","biz","co","com","coop","edu","gov","int","museum","net","org"),"mx" to LeavesTldNode("com","org","gob","edu","net"),"my" to LeavesTldNode("biz","com","edu","gov","mil","name","net","org"),"mz" to LeavesTldNode("ac","adv","co","edu","gov","mil","net","org"),TldNode.childless("madrid"),TldNode.childless("maif"),TldNode.childless("maison"),TldNode.childless("makeup"),TldNode.childless("man"),TldNode.childless("management"),TldNode.childless("mango"),TldNode.childless("map"),TldNode.childless("market"),TldNode.childless("marketing"),TldNode.childless("markets"),TldNode.childless("marriott"),TldNode.childless("marshalls"),TldNode.childless("mattel"),TldNode.childless("mba"),TldNode.childless("mckinsey"),TldNode.childless("med"),TldNode.childless("media"),TldNode.childless("meet"),TldNode.childless("melbourne"),TldNode.childless("meme"),TldNode.childless("memorial"),TldNode.childless("men"),TldNode.childless("menu"),TldNode.childless("merckmsd"),TldNode.childless("miami"),TldNode.childless("microsoft"),TldNode.childless("mini"),TldNode.childless("mint"),TldNode.childless("mit"),TldNode.childless("mitsubishi"),TldNode.childless("mlb"),TldNode.childless("mls"),TldNode.childless("mma"),TldNode.childless("mobile"),TldNode.childless("moda"),TldNode.childless("moe"),TldNode.childless("moi"),TldNode.childless("mom"),TldNode.childless("monash"),TldNode.childless("money"),TldNode.childless("monster"),TldNode.childless("mormon"),TldNode.childless("mortgage"),TldNode.childless("moscow"),TldNode.childless("moto"),TldNode.childless("motorcycles"),TldNode.childless("mov"),TldNode.childless("movie"),TldNode.childless("msd"),TldNode.childless("mtn"),TldNode.childless("mtr"),TldNode.childless("music"))
    }
}